#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  piston,         sensorDigitalOut)
#pragma config(Sensor, dgtl12, light,          sensorDigitalOut)
#pragma config(Sensor, I2C_1,  Swings,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port9,           wings,         tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int iWingTop = 100;
const int iWingDown = 25;

const int iWingTime = 1000;
const int iPistonTime = 1500;

bool bAutomated = false;

void waitForRelease(){
	while(vexRT[Btn8R]){
		wait1Msec(10);
	}
}

void statusLight(){
	if(bAutomated){
		SensorValue[light] = true;
	}else{
		SensorValue[light] = false;
	}
}

void checkAutomated(){
	if(vexRT[Btn8R]){
		if(bAutomated){
			bAutomated = false;
		}else{
			bAutomated = true;
		}
		waitForRelease();
	}
}

task flapWing(){

	while(true){
		if(bAutomated){
			while(SensorValue[Swings] < iWingTop){
				motor[wings] = 25;
			}
			SensorValue[piston] = false;

			while(SensorValue[Swings] > iWingDown){
				motor[wings] = -15;
			}
			SensorValue[piston] = true;

			motor[wings] = 0;
			checkAutomated();

			wait1Msec(10);
		}
	}
}

task OpControl(){
	while(true){
		if(!bAutomated){
			motor[wings] = vexRT[Ch2];

			if(vexRT[Btn6U]){
				SensorValue[piston] = true;
			}else if(vexRT[Btn6D]){
				SensorValue[piston] = false;
			}

			checkAutomated();
		}

		wait1Msec(10);
	}
}

task main()
{
	SensorValue[Swings] = 0;
	startTask(flapWing);
	startTask(OpControl);
	while(true){
		statusLight();
		wait1Msec(10);

		if(vexRT[Btn7D]){
			SensorValue[Swings] = 0;
		}
	}
}
